const MIN_DURATION = 1;
const MAX_DURATION = 180;
const MIN_NUMBER_OF_PROBLEMS = 1;
const MAX_NUMBER_OF_PROBLEMS = 5;
const MIN_PROBLEM_POINTS = 1;
const MAX_PROBLEM_POINTS = 100;

module.exports = {
  MIN_DURATION,
  MAX_DURATION,
  MIN_NUMBER_OF_PROBLEMS,
  MAX_NUMBER_OF_PROBLEMS,
  MIN_PROBLEM_POINTS,
  MAX_PROBLEM_POINTS,
};
